title: GAME TITLE
description: Tagline that captures the essence of your game
baseurl: "" # for subfolder sites
url: "" # your domain or GitHub Pages URL

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Custom variables
game_title: GAME TITLE
social_links:
  twitter: yourtwitter
  github: yourgithub

# Collections
collections:
  team:
    output: true
